image: debian/oldstable

packages:
  - curl
  - gcc
  - mingw-w64

tasks:

  - build-bloghead: |
      curl -L 'https://go.dev/dl/go1.19.3.linux-amd64.tar.gz' > go.tar.gz
      tar -xf go.tar.gz && rm go.tar.gz
      cd bloghead
      PATH=$PATH:~/go/bin make linux

  - build-bloghead-exe: |
      cd bloghead
      PATH=$PATH:~/go/bin make windows

artifacts:
  - bloghead/dist/bloghead
  - bloghead/dist/bloghead.exe
