image: debian/oldstable

packages:
  - curl
  - gcc
  - luarocks
  - mingw-w64

tasks:
  - build-djotbin: |
      luarocks install luastatic --local
      cd bloghead/djot
      ~/.luarocks/bin/luastatic\
        bin/main.lua\
        djot.lua\
        djot/ast.lua\
        djot/attributes.lua\
        djot/block.lua\
        djot/emoji.lua\
        djot/html.lua\
        djot/inline.lua\
        djot/json.lua\
        djot/match.lua\
        /usr/lib/x86_64-linux-gnu/liblua5.1.a\
        -I /usr/include/lua5.1\
        -o ../blogfs/djotbin

  - build-djotbin-exe: |
      cd bloghead/djot
      CC=x86_64-w64-mingw32-gcc ~/.luarocks/bin/luastatic\
        bin/main.lua\
        djot.lua\
        djot/ast.lua\
        djot/attributes.lua\
        djot/block.lua\
        djot/emoji.lua\
        djot/html.lua\
        djot/inline.lua\
        djot/json.lua\
        djot/match.lua\
        ../vendored/lua-5.4.2_Win64_mingw6_lib/liblua54.a\
        -I ../vendored/lua-5.4.2_Win64_mingw6_lib/include\
        -o ../blogfs/djotbin.exe -static

  - build-bloghead: |
      curl -L 'https://go.dev/dl/go1.19.3.linux-amd64.tar.gz' > go.tar.gz
      tar -xf go.tar.gz && rm go.tar.gz
      cd bloghead
      ~/go/bin/go build

  - build-bloghead-exe: |
      cd bloghead
      CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows ~/go/bin/go build

artifacts:
  - bloghead/bloghead
  - bloghead/bloghead.exe
  - bloghead/blogfs/djotbin
  - bloghead/blogfs/djotbin.exe
