image: debian/oldstable

packages:
  - curl
  - gcc
  - mingw-w64
  - zip

tasks:
  - make-linux: |
      curl -L 'https://go.dev/dl/go1.19.3.linux-amd64.tar.gz' > go.tar.gz
      tar -xf go.tar.gz && rm go.tar.gz
      cd bloghead
      PATH=$PATH:~/go/bin make linux
      cd dist
      zip -r bloghead-linux.zip linux

  - make-windows: |
      cd bloghead
      PATH=$PATH:~/go/bin make windows
      cd dist
      zip -r bloghead-windows.zip windows

artifacts:
  - bloghead/dist/bloghead-linux.zip
  - bloghead/dist/bloghead-windows.zip
