-- combine modules into one file
-- https://github.com/jgm/djot/issues/79#issuecomment-1306378644
print([[
-- Autogenerated by vendor-djot.lua. Do not edit.

-- https://github.com/jgm/djot/blob/main/LICENSE
-- Copyright (C) 2022 John MacFarlane
--
-- Permission is hereby granted, free of charge, to any person obtaining
-- a copy of this software and associated documentation files (the
-- "Software"), to deal in the Software without restriction, including
-- without limitation the rights to use, copy, modify, merge, publish,
-- distribute, sublicense, and/or sell copies of the Software, and to
-- permit persons to whom the Software is furnished to do so, subject to
-- the following conditions:
--
-- The above copyright notice and this permission notice shall be included
-- in all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-- EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
-- IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
-- CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
-- TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-- SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]])


local modules = {"djot", "djot.ast", "djot.attributes", "djot.block",
                 "djot.emoji", "djot.html", "djot.inline", "djot.json",
                 "djot.match"}

for _,module in ipairs(modules) do
  print(string.format('package.preload["%s"] = function()', module))
  local path = "djot/" .. module:gsub("%.","/") .. ".lua"
  local f = assert(io.open(path, "r"))
  local content = f:read("*all")
  print(content)
  print('end\n')
end

print([[
local djot = require("djot")
function djot_to_html (input)
    local parser = djot.Parser:new(input)
    parser:parse()
    local html = parser:render_html()
    return html
end]])
